name: EasyRecipes
version: '1.0'
main: io.github.Earth1283.easyRecipes.EasyRecipes
api-version: '1.21'
load: STARTUP
description: Returning pre-1.21 raids to 1.21 servers!
commands:
  easyrecipesreload:
    description: Reloads the custom recipes from the config file.
    usage: /easyrecipesreload
    permission: easyrecipes.reload

permissions:
  easyrecipes.reload:
    description: Allows reloading of the recipes config.
    default: op